### ISSUE TITLE
Consider Publishing as ES5

### ISSUE THREAD

**Issue by mattdesl** [transitive-bullshit/random#3]
I'm just trying to use your module but it seems to require some dependency called `esm` — I think a better solution might be to just transpile to ES5 compatible code so that users can just `require('random')` or `import 'random'` in node and browserify.

**Comment by transitive-bullshit** [comment]
Yeah, that's on my short list of TODOs, though the entire point of esm is that you should be able to use the module in the way you described, either from commonjs `require('random')` or esm `import 'random'`, so I'm not sure why it isn't working for you.

It's likely I messed something up in the configuration.  Would you mind giving me a little more info on how you're trying to use the module? (with environment, bundler, versions, etc.)

Thanks!

**Comment by mattdesl** [comment]
`esm` seems like some sort of experimental Node-only module loader, I don't see anything about it working in the browser.

You can reproduce the issue like so in Node, in a clean folder:

```sh
npm init -y
npm install random
node -e "require(\"random\")"
```

Error:

```
Error: Cannot find module 'esm'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/matt/Desktop/foobarc/node_modules/random/index.js:5:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

You can also get the same error with browserify:

```sh
# the '-' indicates the input is coming from a piped stream
echo "require(\"random\")" | browserify -
```

Or, to test:

```sh
browserify -r random
```

I think common practice for a node+browser module would be to publish as ES5 instead of relying on a module loader. So when this is brought into a browser, the code should just be the random generator functions, rather than additional opinionated module loading which may conflict with current browser tools (webpack, rollup, browserify, etc). To publish ES5 on `prepublishOnly` hook, some people use webpack, rollup, [microbundle](https://www.npmjs.com/package/microbundle) etc.

Also, just wanted to let you know that [ow](https://www.npmjs.com/package/ow) leads to about 50kb of JavaScript after minification in the browser... sadly there is 0% chance I would ever be able to include a module like `random` in a real web app, because it is currently so heavy. Nevertheless, it's still cool, and I can use the open source code to re-implement the same functions in my own browser-friendly modules.

**Comment by mattdesl** [comment]
Ok, looks like it's because `esm` is a devDependency instead of regular dependency. Unfortunately, it still doesn't seem to work in the browser even after fixing that, since `esm` doesn't appear to be browser or browserify friendly.

**Comment by transitive-bullshit** [comment]
Yep, that was the issue for node.js, though the browser version isn't using `esm`.  I'm compiling it with rollup+babel into `dist/browser.js`, though I haven't tested the browser version yet.

**Comment by transitive-bullshit** [comment]
> Also, just wanted to let you know that ow leads to about 50kb of JavaScript after minification in the browser... sadly there is 0% chance I would ever be able to include a module like random in a real web app, because it is currently so heavy. Nevertheless, it's still cool, and I can use the open source code to re-implement the same functions in my own browser-friendly modules.
Nooooo haha, we should work together to fix this issue so everyone can benefit from a small, consistent module :)

I'll create an issue over at `ow` with regards to making that smaller, cause 50kb minified is outrageous for that lib. I suppose in the meantime, I could make `ow` a node-only dependency and shim `ow` with a noop module for the browser version.  Thoughts?

**Comment by transitive-bullshit** [comment]
This is all great feedback btw; sorry for all the stumbling blocks, as this is a very new module.

**Comment by transitive-bullshit** [comment]
Just an update here, `random@0.0.12` is now bundled as ES5 without the use of `esm`, and I've replaced the use of `ow` with [ow-lite](https://github.com/transitive-bullshit/ow-lite).

| Library         | Size      | Minified | GZip     |
|:----------------|:----------|:---------|:---------|
| `random@2.0.8`  | 172.33 KB | 79.32 KB | 20.25 KB |
| `random@2.0.12` | 62.79 KB  | 15.82 KB | 3.54 KB  |

**Comment by mattdesl** [comment]
Awesome!! 👍
