### ISSUE TITLE
random.normal returns negative number..

### ISSUE THREAD

**Issue by hpl002** [transitive-bullshit/random#30]
Seemingly fairly easy to break..

``` JS
const random = require('random');

let mean = 300
let sd = 100

let res = 1
let counter = 0;
while (res>0) {
    const s = random.normal(mean, sd)
     res = Math.round(s())
     counter = counter+1;
}
console.log("broke after num tries:", counter)

```

**Comment by hpl002** [comment]
hotfix being to simply try again if negative..

Not a huge deal, but would be nice with a patch or notice

**Comment by transitive-bullshit** [comment]
Hey Herman, thanks for bringing this up.

I’m not sure I see where the issue / break is in your example.

Is it not producing a normal distribution of numbers? With a normal dist centered at 300 and std of 100, returning negative numbers sometimes is expected.

Can you provide more detail as to what you’re seeing that’s not expected?

Thanks.
