### ISSUE TITLE
Add random.choice

### ISSUE THREAD

**Issue by BbayuGt** [transitive-bullshit/random#33]
Just like python `random`, making `random.choice` is a pretty good thing. just for a simplicity.

Example :
array : `["a", "b"]`
Instead of doing
```js
array[random.int(0,1)] // return "a"
```
isn't it better if you could do :
```js
random.choice(array) // return "a"
```

I know some of you'll like "you can make it yourself". But isn't this why this module created?

**Comment by transitive-bullshit** [comment]
Thanks @BbayuGt && sorry for taking so long. `random.choice` is now in `4.1.0` 🚀
