### ISSUE TITLE
Cannot create `Random` with custom seed function (named exports of CJS module are inconsistent with TypeScript types)

### ISSUE THREAD

**Issue by cowboyd** [transitive-bullshit/random#35]
The following typechecks

```ts
import { RNGFactory, Random } from 'random';
import seedrandom from 'seedrandom';

RNGFactory(seedrandom('random seed'));
```

But `RNGFactory` is not actually exported. Commenting out this line fixes it https://github.com/transitive-bullshit/random/blob/master/src/index.ts#L5-L8

I'm curious why this was necessary in the first place?

**Comment by cowboyd** [comment]
For what it's worth, here is my tsconfig:

```
$ npx tsc --showconfig
{
    "compilerOptions": {
        "target": "es2019",
        "moduleResolution": "node",
        "strict": true,
        "module": "commonjs",
        "skipLibCheck": true,
        "sourceMap": true,
        "declaration": true,
        "esModuleInterop": true,
        "rootDir": "./",
        "noEmit": true
    },
    "files": [
        "./src/distribution.ts",
        "./src/index.ts",
        "./test/cyclic.test.ts",
        "./test/graphgen.test.ts",
        "./test/normal.test.ts"
    ],
    "include": [
        "src",
        "test"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by agmoss** [comment]
Hi @cowboyd! 

Thanks for bringing this up. I have never been overly happy with the typescript build of this package. I will take a stab at a building improvement that will remedy the issue.

**Comment by cowboyd** [comment]
Since this is compiled with `tsconfig.cjs.json` which has the node module type set as `commonjs`, I'm wondering if it could be as simple as just removing this code?

**Comment by cowboyd** [comment]
Not sure if this solution is "ideal", but it does allow us to have our CJS cake and eat it with ESM utensils #36

**Comment by agmoss** [comment]
There doesn't seem to be a clear way to facilitate esm/cjs default export interoperability. Babel can fix this, but its inclusion here seems excessive. 

Publishing this library with the requirement of a `.default` property to `require()` would simplify the build tooling but this is cumbersome for cjs users. 

I took a look at your solution and tested it. I think it is a good simple solution to the problem. It would be nice to get rid of the separate `index.ts` and `index.esm.ts` entry points. Do you think that is possible? 

Related: https://github.com/microsoft/TypeScript/issues/2719

**Comment by cowboyd** [comment]
> It would be nice to get rid of the separate index.ts and index.esm.ts entry points. Do you think that is possible?

I think it's possible, but honestly I would keep the CJS compatibility separate from the rest of the code so that it can be easily removed at some point. What about moving `index.esm.ts` -> `index.ts` and then having a `index.cjs.ts` that imports from `index.ts` and does this hack for compatibility? That way the ESM is the clean path, and `index.cjs.ts` is a shim for those who will consume the module from CJS:

```ts
// index.cjs.ts
// Support require() from CJS
import * as symbols from '.';
import random from '.';

// do this so that types will line up in `index.cjs.d.ts`
export * from '.';
export default random;

Object.assign(random, symbols);
module.exports = random;
```

**Comment by agmoss** [comment]
This makes perfect sense. I think it's a good idea to provide a clear path of deprecation for the cjs support. Swapping the `index` files as proposed is a good inclusion for the future maintainability of the package.

**Comment by cowboyd** [comment]
@agmoss Ok, I went ahead and did this in #36 and opened it up for review.

**Comment by transitive-bullshit** [comment]
This should be resolved in `v4` as we no longer export CJS.
