### ISSUE TITLE
How to specify a seed

### ISSUE THREAD

**Issue by AndreasChristianson** [transitive-bullshit/random#37]
I expected that after setting the same seed, the behavior of both clones would be the same. Unfortunately the following test fails.
```
import random from "random"

describe('random', () => {
  it('should be predictable', () => {
    const rand1 = random.clone("abc");
    const rand2 = random.clone("abc");
    
    expect(rand1.float()).toEqual(rand2.float());
  });
});
```

Am I using `clone` incorrectly? 

I'm pretty close to the example from the readme:
```
...
// create a new independent random number generator (uses seedrandom under the hood)
const rng = random.clone('my-new-seed')
...
```

**Comment by jsalvata** [comment]
There's a bug [here](https://github.com/transitive-bullshit/random/blob/master/src/rng-factory.ts#L29) -- should read `seedrandom(...args)` instead of `seedrandom(...rest)`.

Until it is fixed, you can work around it using:
```
const rng = random.clone(seedrandom('my-new-seed'));
```

**Comment by transitive-bullshit** [comment]
Fixed in https://github.com/transitive-bullshit/random/commit/4243d10c8139fe18878f4b186ad18ff67cac789c

Sorry for taking so long; please upgrade to v4 for future use.
