### ISSUE TITLE
Predictable pseudo random number 

### ISSUE THREAD

**Issue by yanickrochon** [transitive-bullshit/random#5]
I expected this module to return the same sequence of random numbers if seeded with the same value. But it seems completely unpredictable. I'm I missing something?

```js
const rng = random.clone(seed).uniform();

rng();
rng();
rng();
```

I would've expected the three `rnd()` calls to return the same random numbers every time.

**Comment by transitive-bullshit** [comment]
This was definitely a bug; sorry about that.

I just published a fix that hopefully resolves your issue as `v2.1.1`.

**Comment by yanickrochon** [comment]
Thank you, but unfortunately it does not. The same example provided in this issue always returns different values, even giving the same `seed`.

**Comment by frankiesimon** [comment]
Will this be resolved?

**Comment by pieterdb4477** [comment]
Same issue here.

Fortunatly this problem seems to be solved when using seedrandom explicitly:

```
// always random
const rng = random.clone('my-new-seed')
 
// always the same results
const rng2 = random.clone(seedrandom('kittyfoo'))
```

**Comment by transitive-bullshit** [comment]
Just tested with `v4` and this has been resolved after this fix https://github.com/transitive-bullshit/random/commit/4243d10c8139fe18878f4b186ad18ff67cac789c
