### ISSUE TITLE
QRNG support? 🙄

### ISSUE THREAD

**Issue by couldbejake** [transitive-bullshit/random#50]

**Comment by transitive-bullshit** [comment]
Hey Jake, not sure what QRNG is, but `random` does support custom PRNG functions. Could you provide an example of what you're looking for that's not currently possible?

**Comment by couldbejake** [comment]
Hi Transitive, QRNG is essentially the generation of non pseudo random cryptographically secure raw binary data.

I made this request in jest as I understand individuals clearly do not have access to quantum computers, but for support for the future and actual utility you should prepare your library for the ingestion of 1 qubit device generated random numbers.

It's a big industry and things are changing fast, any numbers generated via a processor are not secure knowing the states of the starting condition(s).
