### ISSUE TITLE
Unexpected failsafe in Random constructor

### ISSUE THREAD

**Issue by ProgMiner** [transitive-bullshit/random#53]
Hello!

I noticed that `Random` constructor just ignores argument if it is not `RNG` without any error message: https://github.com/transitive-bullshit/random/blob/8bdcdd8203f231a50df1f81d07ae64a10a1a5043/src/random.ts#L64

Maybe it will be more helpful to throw `Error` or raise some `console.error` message in this case, to not mislead users.

Second thing is that README suggests use following code to specify seed:
```js
import { Random } from 'random'
import seedrandom from 'seedrandom'

const rng = new Random()
const rng2 = new Random(seedrandom('tinykittens'))
```

And this isn't correct because of that check in constructor.

Best regards,
ProgMiner

**Comment by transitive-bullshit** [comment]
This has been fixed in the latest release. Thanks!
