### ISSUE TITLE
new feature request: improve choice

### ISSUE THREAD

**Issue by hassifmohd** [transitive-bullshit/random#54]
I have a request: Can the `choice()` function be enhanced to retrieve more than one option?

`random.choices(data: array, choices: number, isUnique: boolean = true)`

example:

```
random.choices([1, true, 'foo'], 3) //return: true, 'foo', 1

random.choices([1, true, 'foo'], 3, false) //return: true, 'foo', 'foo'
```

**Comment by transitive-bullshit** [comment]
Not sure I'm a fan of these types of varargs, but I appreciate the suggestion.
