### ISSUE TITLE
Security: breaks when CSP is enabled

### ISSUE THREAD

**Issue by ivan-aksamentov** [transitive-bullshit/random#6]
When runing in a browser, with a [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) enabled, which does not allow `eval` (which is every decent policy), this package breaks the application.

I receive the following error in Chromium:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".

    at eval (<anonymous>)
    at seedrandom.js:32
    at Object../node_modules/seedrandom/seedrandom.js (seedrandom.js:25)
    at Object../node_modules/seedrandom/index.js (index.js:51)
    at Object../node_modules/random/dist/rng-factory.js (rng-factory.js:1)
    at Object../node_modules/random/dist/random.js (random.js:4)
```

It seems that the `eval()` comes from `seedrandom` package and it has been fixed a few months ago there:
https://github.com/davidbau/seedrandom/issues/64
https://github.com/davidbau/seedrandom/pull/65

Could you please upgrade `seedrandom` to the latest version?

**Comment by transitive-bullshit** [comment]
Updated all deps and released as `v2.2.0`.

Thanks!
