### ISSUE TITLE
PRNG vs RNG

### ISSUE THREAD

**Issue by JeDeveloper** [transitive-bullshit/random#61]
When I try to compile the code from the example using typescript
```
import { Random } from 'random'
import seedrandom from 'seedrandom'

const rng = new Random()
const rng2 = new Random(seedrandom('tinykittens'))
```

I get the following error 
`TS2345: Argument of type 'PRNG' is not assignable to parameter of type 'RNG'.`

**Comment by transitive-bullshit** [comment]
This is now fixed in https://github.com/transitive-bullshit/random/releases/tag/v5.0.0 (added unit tests to ensure the types are now fixed). Thanks!
