### ISSUE TITLE
Issue with browser usage

### ISSUE THREAD

**Issue by justinfagnani** [transitive-bullshit/random#63]
While this package is published as standard modules, seedrandom isn't, so [this line](https://github.com/transitive-bullshit/random/blob/master/src/rng-factory.ts#L1) fails in browsers. See the console error in [my attempt at a live demo](https://lit.dev/playground/#project=W3sibmFtZSI6InJhbmRvbS1udW1iZXIudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHN0YXRlfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgcmFuZG9tIGZyb20gJ3JhbmRvbSc7XG5cbkBjdXN0b21FbGVtZW50KCdyYW5kb20tbnVtYmVyJylcbmV4cG9ydCBjbGFzcyBSYW5kb21OdW1iZXIgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICA6aG9zdCB7XG4gICAgICBjb2xvcjogYmx1ZTtcbiAgICB9XG4gIGA7XG4gIFxuICBAc3RhdGUoKVxuICBwcml2YXRlIF92YWx1ZSA9IHJhbmRvbS5yYW5kb21JbnQoMCwgMTAwKTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIHRoaXMuX3ZhbHVlO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vcmFuZG9tLW51bWJlci5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxyYW5kb20tbnVtYmVyPjwvcmFuZG9tLW51bWJlcj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0).

seedrandom hasn't been updated in a long time, so I'm not sure if it's feasible for it to publish modules also.

**Comment by justinfagnani** [comment]
Looks like there's a modules port of seedrandom here: https://github.com/shanewholloway/js-esm-seedrandom#readme

**Comment by transitive-bullshit** [comment]
I believe this should now be fixed by https://github.com/transitive-bullshit/random/releases/tag/v5.0.0, but please let me know if you're still seeing a repro.

**Comment by transitive-bullshit** [comment]
seedrandom has now been removed as a dep: https://github.com/transitive-bullshit/random/releases/tag/v5.1.0
