### ISSUE TITLE
Some Methods Return [Function]

### ISSUE THREAD

**Issue by andrewtyl** [transitive-bullshit/random#7]
I've tried on multiple versions, and random.uniform and random.normal do not return numbers, but return [Function].

**Comment by transitive-bullshit** [comment]
They all return a function so that you can have a consistent seed if you want to generate multiple random numbers in a row.

Just invoke the returned function to get the random numbers you want.

**Comment by monkworker** [comment]
`random.bernoulli(p)` returns a function. What happens if I change the 'p' value? A new function is returned, and the seed remains the same?

**Comment by transitive-bullshit** [comment]
It's up to you to change the underlying RNG if you create multiple instances of distribution functions. They'll re-use the same RNG by default.
